name: Keep Backend Service Active

on:
  schedule:
    - cron: '*/3 * 1 9 *'
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -f ${{ secrets.BACKEND_URL }}/health
