name: Keep Frontend Service Active

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping frontend
        run: curl -f ${{ secrets.FRONTEND_URL }}  